<a href="https://colab.research.google.com/github/Abhi050/DL_Tutorials-PyTorch-/blob/master/01_tensor_operations.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Assignment - 1(Introduction to Tensors in Pytorch and some of their interesting function)

Pytorch is an open source machine learning library based on the torch package. It was primarily developed by FaceBook's AI research team. They provide with end to end research framework. In addition to the framework they allow chaining of high-level nueral network modules since it supports Keras like API in its torch.nn (help in creating and training of the neural network) package. Pytorch is mainly employed for application such as the Computer Vision (use of image processing algorithms to gain high-level understanding from digital images or videos) and Natural Language Processing (ability of a computer program to understand human language).

- new_full(size, fill_value, dtype=None, device=None, requires_grad=False)
- torch.ne(input, other, out=None) → Tensor
- torch.cat()
- gather()
- torch.flatten()

In [0]:
# Import torch and other required modules
import torch
import numpy as np

## Function 1 -new_full(size, fill_value, dtype=None, device=None, requires_grad=False)

This function is used to return a tensor with a specified size and is filled with a specific value given as input. The output tensor will have the default datatype which can be also be manipulated.

The parameters of the function are :-

(i) device (torch.device, optional) – the desired device of returned tensor. By default the value is set as if None, same torch.device as this tensor.

(ii) requires_grad (bool, optional) – If autograd should record operations on the returned tensor. By default the value is set as False.

(iii) fill_value (scalar) – the number to fill the output tensor with.

(iv) dtype (torch.dtype, optional) – the desired type of returned tensor. By default the value is if None, same torch.dtype as this tensor.



In [0]:
# Example 1 - working
t=torch.zeros([3, 3],dtype=torch.float64)
print(t)
t.new_full([2,4],0.112)


tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]], dtype=torch.float64)


tensor([[0.1120, 0.1120, 0.1120, 0.1120],
        [0.1120, 0.1120, 0.1120, 0.1120]], dtype=torch.float64)

In above example we can see that first we created a tensor which has three columns and rows and is filled with zeros using the function torch.zeros() it is also specified that it has the datatype torch.float64. Now we use this tensor to create a new one with a different size and is filled its elements with a scalar quantity.

In [0]:
# Example 2 - working
t=torch.ones([4, 4],dtype=torch.int64)
t.new_full([3,3],999)

tensor([[999, 999, 999],
        [999, 999, 999],
        [999, 999, 999]])

In above example we can see that first we created a tensor which has four columns and rows and is filled with ones using the function torch.ones() it is also specified that it has the datatype torch.int64. Now we use this tensor to create a new one with a different size and is filled its elements with a scalar quantity.

In [0]:
# Example 3 - breaking (to illustrate when it breaks)
t=torch.ones([4, 4],dtype=torch.float64)
t.new_full([3,3],0.11234)

tensor([[0.1123, 0.1123, 0.1123],
        [0.1123, 0.1123, 0.1123],
        [0.1123, 0.1123, 0.1123]], dtype=torch.float64)

in doing so it dont consider or round off ant value after 4th decimal place

This functon is really is useful in creating a new tensor of any shape and datatype from a pre-defined tensor.

## Function 2 - torch.ne(input, other, out=None) → Tensor

This function is used for element-wise comparing the two tensors. Returns False at the tensor positions where the elements match and True at the other places


In [0]:
# Example 1 - working
torch.ne(torch.tensor([[1,2,3],[1,2,3]]),torch.tensor([[1,2,2],[1,1,3]]))

tensor([[False, False,  True],
        [False,  True, False]])

Element wise comparison is done and False is returned for not same values and True is returned for same values.

In [0]:
# Example 2 - working
torch.ne(torch.tensor([[1.,2,3],[1.,2,3]]),torch.tensor([[1,2,2],[1,1,False]]))

tensor([[False, False,  True],
        [False,  True,  True]])

During comparison 1. is equal to 1 and True.

In [0]:
# Example 3 - breaking (to illustrate when it breaks)
torch.ne(torch.tensor([[1,2,3],[1,2,3]]),torch.tensor([[1,2,2,2],[1,1,3,2]]))

RuntimeError: The size of tensor a (3) must match the size of tensor b (4) at non-singleton dimension 1

Here arguments input and other do not have same dimesnions and hence can't be compared elementwise.

This function can be used to comapre if the two tensors have same value at resective positions

## Function 3 - torch.cat()

This function is used to concatenate tensors along the required axis to create new tensors.Two tensors of the same size on all the dimensions except one, if required, can be concatenated using this function.

In [0]:
# Example 1 - working
a = torch.tensor([[1,1,1],[2,2,2]])
b = torch.tensor([[3,3,3],[4,4,4]])
c = torch.cat((a,b),dim=0)
print(c)
print(a.shape)
print(b.shape)
print(c.shape)

tensor([[1, 1, 1],
        [2, 2, 2],
        [3, 3, 3],
        [4, 4, 4]])
torch.Size([2, 3])
torch.Size([2, 3])
torch.Size([4, 3])


The two tensors are joined along the axis 1 forming a 4 x 3 matrix

In [0]:
# Example 2 - working
a = torch.tensor(data = [i for i in range(9)]).reshape(3,3) #Create a 3x3 matrix ie a tensor of rank 2
b = torch.tensor(data = [i for i in range(9,18)]).reshape(3,3)

c = torch.cat((a,b),dim=1)
c
c.shape


torch.Size([3, 6])

The two tensors are joined along the axis 1 forming a 3 x 6 matrix

In [0]:
# Example 3 - breaking (to illustrate when it breaks)
#Create a 3x3 matrix ie a tensor of rank 2
a = torch.tensor(data = [i for i in range(6)]).reshape(2,3) 
b = torch.tensor(data = [1,1,1]).reshape(3,1)

c = torch.cat((a,b),dim=0)

RuntimeError: Sizes of tensors must match except in dimension 0. Got 3 and 1 in dimension 1

There we are trying to concatenate a 3 x 3 matrix with 3 x 1 matix along axis 0 which results in shape mismatch.This operation will work if we change the axis to 1,because the the new tensor will have a valid mathematical shape.



can be used to concatenate two or more tensors

## Function 4 - torch.gather(input, dim, index)

For a 2-D Tensor, the output matrix will be

    (i)if dim = 0
        outi = inputindex[i][j]

    (ii)if dim = 1
        outi = inputiindexi]

In [0]:
# Example 1 - working
a = torch.tensor([[1,2],[3,4]])
b = torch.tensor([[0,0],[1,0]])

print(torch.gather(a,0, b))
print(torch.gather(a,1, b))

tensor([[1, 2],
        [3, 2]])
tensor([[1, 1],
        [4, 3]])


In [0]:
# Example 2 - working
a = torch.randint(1,10, (3,3,3))
b = torch.randint(0,3,(3,3,3))
torch.gather(a,2,b)

tensor([[[1, 1, 1],
         [8, 8, 8],
         [5, 4, 4]],

        [[3, 6, 3],
         [7, 7, 7],
         [4, 6, 4]],

        [[3, 3, 9],
         [7, 6, 7],
         [5, 5, 4]]])

In [0]:
# Example 3 - breaking (to illustrate when it breaks)
b = torch.randint(0,4, (3,3,3))
torch.gather(a,2,b)

RuntimeError: index 3 is out of bounds for dimension 2 with size 3

The index matrix should contain only the index values of the input tensor. The dimensions of the input tensor is (3,3,3), hence the index tensor must consist values from 0 to 2.

## Function 5 - torch.flatten(input, start_dim=0, end_dim=-1)

This function flattens a contiguous range of dims in a tensor. The first arguement ('input') refers to the input tensor. The second arguement ('start_dim') should be an integer which refers to the first dim to flatten. The third arguement ('end_dim') should be an integer which refers to the last dim to flatten.

In [0]:
# Example 1 - working
a = torch.tensor(data = [i for i in range(6)]).reshape(2,3) 
f = torch.flatten(a)
f

tensor([0, 1, 2, 3, 4, 5])

tensor a is flatten into singular dimension

In [0]:
# Example 2 - working
a = torch.randn(4,5)
print(a)

b = torch.flatten(a)
b

tensor([[-0.2039,  0.5800, -0.5503,  0.9636, -0.4586],
        [-0.9590,  0.7324, -1.4858, -1.4612,  0.2740],
        [-0.2636,  0.0457,  0.5671,  0.7687,  0.9013],
        [ 0.1521,  1.0148,  1.2017,  0.2834,  0.1323]])


tensor([-0.2039,  0.5800, -0.5503,  0.9636, -0.4586, -0.9590,  0.7324, -1.4858,
        -1.4612,  0.2740, -0.2636,  0.0457,  0.5671,  0.7687,  0.9013,  0.1521,
         1.0148,  1.2017,  0.2834,  0.1323])

tensor a is flatten into singular dimension

In [0]:
# Example 3 - breaking (to illustrate when it breaks)
a = torch.randn(4,5)
print(a)

b = torch.flatten(a,end_dim=1.2)
b

tensor([[-0.7782,  1.7946,  1.4016, -0.1922,  0.3915],
        [-1.4406,  0.8352, -0.9240, -1.9324, -0.0682],
        [ 2.9219, -0.3419, -0.6033, -2.1383,  0.3881],
        [-0.6565,  0.8472, -0.3417, -0.4257, -0.1671]])


TypeError: flatten(): argument 'end_dim' must be int, not float

the second argument (start_dim) needs to be an integer.

This function is useful when we want to flatten a contiguous range of dims in a tensor



## Conclusion

This notebook encompass the brief introduction to the Pytorch package its application in the field of machine-learning. This notebook also include some of the functions used in torch package which I found interesting. There is a brief decription of each function along with its parameter description. This is followed by the two working and one broken scenario of each function along with a brief description.

## Reference Links
Provide links to your references and other interesting articles about tensors
* Official documentation for `torch.Tensor`: https://pytorch.org/docs/stable/tensors.html
* ...

In [0]:
!pip install jovian --upgrade --quiet

In [0]:
import jovian

In [0]:
jovian.commit()

<IPython.core.display.Javascript object>

[jovian] Attempting to save notebook..
[jovian] Please enter your API key ( from https://jovian.ml/ ):
API KEY: 